"""Construct conversations/thesis_planning/{corpus.json, ground_truth.json}.

Same method as conversations/marathon_trip/build.py: raw per-node fields are
authored below; recurrence_count, retrieval_count, epistemic_status/history,
entities.mentioned_in, and state_nodes status/last_updated_turn are derived
programmatically.

80 turns over ~7 months with real gaps between sessions: a method decision
reverted and later partly brought back (SN_5 -> SN_7 -> SN_10), a goal
abandoned (SN_4), scope and deadline constraints revised, and research
questions set at N_6 and recalled at N_74 (68 turns later). Outline: outline.md.
"""
import json
from collections import Counter
from pathlib import Path

INITIAL_STATUS = {"goal": "active", "decision": "active", "constraint": "active", "open_question": "open"}
OPEN_DEFAULT_ACTS = {"factual_question", "clarification_request"}

ENTITIES = {
    "E_1": {"type": "person", "name": "Rita"},
    "E_2": {"type": "person", "name": "Prof. Almeida"},
    "E_3": {"type": "organization", "name": "the faculty"},
    "E_4": {"type": "dataset", "name": "FakeRecogna"},
    "E_5": {"type": "dataset", "name": "own PT-PT health-claims set"},
    "E_6": {"type": "model", "name": "BERTimbau"},
    "E_7": {"type": "model", "name": "GPT-4o-mini"},
    "E_8": {"type": "model", "name": "Llama-3.1-8B"},
    "E_9": {"type": "concept", "name": "claim-worthiness detection"},
    "E_10": {"type": "concept", "name": "Cohen's kappa"},
    "E_11": {"type": "venue", "name": "PROPOR 2026"},
    "E_12": {"type": "event", "name": "thesis submission deadline"},
    "E_13": {"type": "event", "name": "midterm presentation"},
    "E_14": {"type": "location", "name": "Portugal"},
    "E_15": {"type": "location", "name": "Brazil"},
    "E_16": {"type": "person", "name": "Duarte"},
    "E_17": {"type": "measurement", "name": "macro-F1"},
    "E_18": {"type": "system", "name": "faculty GPU server"},
    "E_19": {"type": "model", "name": "XLM-R-base"},
    "E_20": {"type": "organization", "name": "Arquivo.pt"},
}

STATE_NODE_DEFS = {
    "SN_1": {"type": "goal", "label": "Submit an MSc thesis on detecting misleading health claims in Portuguese news"},
    "SN_2": {"type": "decision", "label": "RQ1: can models detect misleading health claims in PT news? RQ2: does performance differ between PT-PT and PT-BR?"},
    "SN_3": {"type": "constraint", "label": "Scope limited to European Portuguese (PT-PT) news"},
    "SN_4": {"type": "goal", "label": "Build an own annotated PT-PT dataset of at least 2,000 health claims"},
    "SN_5": {"type": "decision", "label": "Main method: fine-tune BERTimbau"},
    "SN_6": {"type": "constraint", "label": "Compute limited to the faculty GPU server (one 16 GB GPU)"},
    "SN_7": {"type": "decision", "label": "Main method: zero-shot and few-shot LLM classification"},
    "SN_8": {"type": "decision", "label": "Data: FakeRecogna plus 400 own-annotated PT-PT claims as the test set"},
    "SN_9": {"type": "open_question", "label": "Is the own annotation reliable enough to report?"},
    "SN_10": {"type": "decision", "label": "Add a fine-tuned XLM-R-base baseline (fits on 16 GB), at the supervisor's request"},
    "SN_11": {"type": "constraint", "label": "Thesis submission deadline: 30 June"},
    "SN_12": {"type": "decision", "label": "Submit a short paper to PROPOR 2026"},
    "SN_13": {"type": "decision", "label": "Thesis structure: six chapters, related work before method"},
    "SN_14": {"type": "open_question", "label": "Should local Llama-3.1-8B replace GPT-4o-mini for reproducibility?"},
}

LABEL_OVERRIDES = {
    ("SN_3", "N_41"): "Scope covers both European (PT-PT) and Brazilian (PT-BR) Portuguese news (originally: PT-PT only)",
    ("SN_2", "N_42"): "RQ1: can models detect misleading health claims in PT news? RQ2: how well does a classifier built on PT-BR transfer to PT-PT? (originally: RQ2 asked whether performance differs between PT-PT and PT-BR)",
    ("SN_7", "N_55"): "Main method: zero-shot and few-shot LLM classification, compared against a fine-tuned XLM-R-base baseline",
    ("SN_11", "N_64"): "Thesis submission deadline: 15 September, after an approved extension (originally 30 June)",
}

NODES = [
    # ---- Scoping (Feb) -----------------------------------------------------------
    dict(id="N_1", date="2026-02-02",
         q="Hi, I'm Rita, an MSc student. My thesis topic was just approved: 'misinformation in Portuguese news'. My supervisor, Prof. Almeida, says it's far too broad. Can you help me plan it?",
         a="Of course. 'Misinformation in Portuguese news' could be a whole research group's agenda, so the first job is narrowing it to something you can finish in one MSc. We'll plan the thesis in stages: scope, research questions, data, method, then writing.",
         act="request", ents=["E_1", "E_2"], cites=[], hier=[], prag=[],
         creates=["SN_1"], updates=[], relates=[],
         summary="Rita needs to plan an MSc thesis on misinformation in Portuguese news; the topic is too broad.",
         ref="Thesis goal, topic too broad"),
    dict(id="N_2", date="2026-02-02",
         q="How would you narrow it?",
         a="Pick one kind of misinformation. Health claims are a good candidate: there was a huge amount of it in Portuguese media during COVID, fact-checkers labelled much of it, and the harm is concrete.",
         act="suggestion", ents=[], cites=[], hier=[["N_1", "subcase"]], prag=[["N_1", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Suggests narrowing to misleading health claims.",
         ref="Narrow to health claims"),
    dict(id="N_3", date="2026-02-02",
         q="I like that. Health claims it is.",
         a="Great. The thesis is now about misleading health claims in Portuguese news.",
         act="agreement", ents=[], cites=[], hier=[], prag=[["N_2", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Rita agrees to focus on health claims.",
         ref="Health claims agreed"),
    dict(id="N_4", date="2026-02-02",
         q="Next: what makes a good research question?",
         a="One you can answer with the data and time you have, whose answer isn't already known, and that is specific enough to tell whether you answered it.",
         act="factual_question", ents=[], cites=[], hier=[["N_2", "subcase"]], prag=[["N_3", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks what makes a good research question.",
         ref="Good RQ criteria"),
    dict(id="N_5", date="2026-02-02",
         q="Can you give examples for my topic?",
         a="A feasibility question ('can current models detect misleading health claims in Portuguese news, and how well?') and a comparison question, for instance about the two main varieties of Portuguese, where resources are very unequal.",
         act="information", ents=[], cites=[], hier=[["N_4", "subcase"]], prag=[["N_4", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Example RQs: detection feasibility and a Portuguese-variety comparison.",
         ref="Example RQs"),
    dict(id="N_6", date="2026-02-02",
         q="Then my RQs are: RQ1, can models detect misleading health claims in Portuguese news? RQ2, does performance differ between European and Brazilian Portuguese?",
         a="Those are clear and answerable. RQ1 is feasibility, RQ2 is the variety comparison. Write them at the top of your thesis document; everything else should serve them.",
         act="decision", ents=["E_14", "E_15"], cites=[], hier=[["N_5", "subcase"]], prag=[["N_5", "depends_on"]],
         creates=["SN_2"], updates=[], relates=[],
         summary="RQ1 (detection feasibility) and RQ2 (PT-PT vs PT-BR difference) set.",
         ref="RQs set"),
    dict(id="N_7", date="2026-02-09",
         q="I met Prof. Almeida. He liked both RQs, but told me to keep the focus on European Portuguese, since that's the gap.",
         a="Makes sense: PT-BR has far more resources, so PT-PT is where a contribution is most needed.",
         act="information", ents=["E_2", "E_14"], cites=[], hier=[], prag=[["N_6", "references"]],
         creates=[], updates=[], relates=[["SN_2", "supports"]],
         summary="Supervisor approves the RQs and asks for a PT-PT focus.",
         ref="Supervisor: focus PT-PT"),
    dict(id="N_8", date="2026-02-09",
         q="So I limit the scope to European Portuguese news only?",
         a="Yes: scope limited to PT-PT news. RQ2 can still use PT-BR material as a point of comparison later if needed.",
         act="decision", ents=["E_14"], cites=[], hier=[["N_6", "subcase"]], prag=[["N_7", "depends_on"]],
         creates=["SN_3"], updates=[], relates=[],
         summary="Scope limited to PT-PT news.",
         ref="Scope: PT-PT only"),
    dict(id="N_9", date="2026-02-09",
         q="Which Portuguese outlets should I collect from?",
         a="Pick outlets that fact-checkers cover, so you can get labels.",
         act="factual_question", ents=[], cites=[], hier=[["N_8", "subcase"]], prag=[["N_8", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks which PT-PT outlets to collect from.",
         ref="Which outlets?"),
    dict(id="N_10", date="2026-02-09",
         q="Which ones do fact-checkers cover most?",
         a="Público, Observador, Expresso and Jornal de Notícias, plus claims the fact-checker Polígrafo has already rated, which gives you labels for free.",
         act="information", ents=[], cites=[], hier=[["N_9", "subcase"]], prag=[["N_9", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Suggested outlets: Público, Observador, Expresso, JN, plus Polígrafo ratings.",
         ref="Outlets listed"),
    dict(id="N_11", date="2026-02-09",
         q="Many 2020–2021 articles are gone from the sites. How do I get older ones?",
         a="Arquivo.pt, the Portuguese web archive, has most of them, and it has an API for bulk access.",
         act="follow_up", ents=["E_20"], cites=[], hier=[["N_9", "same_level"]], prag=[["N_10", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Older articles can be retrieved from Arquivo.pt.",
         ref="Use Arquivo.pt"),
    dict(id="N_12", date="2026-02-09",
         q="Oh, and the submission deadline is 30 June.",
         a="Then we have about 21 weeks. Let's plan backwards: data by mid-April, experiments by the end of May, writing in June.",
         act="information", ents=["E_12"], cites=[], hier=[["N_1", "subcase"]], prag=[],
         creates=["SN_11"], updates=[], relates=[],
         summary="Submission deadline is 30 June.",
         ref="Deadline 30 June"),
    # ---- Literature review (Feb-Mar) ---------------------------------------------------
    dict(id="N_13", date="2026-02-16",
         q="Starting the literature review. Where do I begin?",
         a="With claim detection, the task your RQ1 is about.",
         act="factual_question", ents=["E_9"], cites=[], hier=[["N_2", "subcase"]], prag=[["N_6", "references"]],
         creates=[], updates=[], relates=[],
         summary="Starts the literature review with claim detection.",
         ref="Lit review start"),
    dict(id="N_14", date="2026-02-16",
         q="What's the core literature on claim detection?",
         a="The CheckThat! lab series is the anchor: claim-worthiness detection and verification tasks, several languages, strong baselines to cite.",
         act="information", ents=["E_9"], cites=[], hier=[["N_13", "subcase"]], prag=[["N_13", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="CheckThat! lab is the core claim-detection literature.",
         ref="CheckThat! lab"),
    dict(id="N_15", date="2026-02-16",
         q="Should I also cover full fact-checking pipelines, with evidence retrieval and verdicts?",
         a="Briefly, to position your work: you do detection, not verification. One section is enough.",
         act="follow_up", ents=[], cites=[], hier=[["N_14", "same_level"]], prag=[["N_14", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Full fact-checking pipelines get one positioning section.",
         ref="Pipelines briefly"),
    dict(id="N_16", date="2026-02-23",
         q="Second strand: health misinformation specifically.",
         a="Health misinformation datasets and studies, especially COVID-era ones. This strand justifies the focus you chose in RQ1.",
         act="information", ents=[], cites=[], hier=[["N_13", "same_level"]], prag=[["N_6", "references"]],
         creates=[], updates=[], relates=[],
         summary="Second strand: health misinformation datasets and studies.",
         ref="Health misinfo strand"),
    dict(id="N_17", date="2026-02-23",
         q="Are there Portuguese-specific resources?",
         a="Let's check what exists for each variety.",
         act="factual_question", ents=[], cites=[], hier=[["N_16", "subcase"]], prag=[["N_16", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks about Portuguese-specific resources.",
         ref="PT resources?"),
    dict(id="N_18", date="2026-02-23",
         q="What did you find?",
         a="Very little for PT-PT. For PT-BR there's the Fake.br corpus and the BERTimbau language model, which is trained on Brazilian Portuguese but often used for both.",
         act="information", ents=["E_6", "E_15"], cites=[], hier=[["N_17", "subcase"]], prag=[["N_17", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Few PT-PT resources; PT-BR has Fake.br and BERTimbau.",
         ref="Few PT-PT resources"),
    dict(id="N_19", date="2026-03-02",
         q="Third strand: using LLMs directly as classifiers.",
         a="Zero-shot and few-shot classification with instruction-tuned LLMs, a fast-growing literature, with mixed results on non-English data.",
         act="information", ents=[], cites=[], hier=[["N_13", "same_level"]], prag=[["N_15", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Third strand: LLMs as zero/few-shot classifiers.",
         ref="LLM classifier strand"),
    dict(id="N_20", date="2026-03-02",
         q="Do they work for Portuguese?",
         a="Decently for PT-BR, largely untested for PT-PT. That's another gap your thesis sits in.",
         act="follow_up", ents=["E_14", "E_15"], cites=[], hier=[["N_19", "subcase"]], prag=[["N_19", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="LLMs work decently for PT-BR; PT-PT is largely untested.",
         ref="LLMs on Portuguese"),
    dict(id="N_21", date="2026-03-02",
         q="I found FakeRecogna: a labelled fake-news dataset in Portuguese, including health. But it's all Brazilian.",
         a="Useful, but only PT-BR.",
         act="information", ents=["E_4", "E_15"], cites=[], hier=[["N_17", "subcase"]], prag=[["N_8", "references"]],
         creates=[], updates=[], relates=[],
         summary="Found FakeRecogna, a PT-BR-only labelled dataset.",
         ref="FakeRecogna found"),
    dict(id="N_22", date="2026-03-02",
         q="Can you summarise the literature so far?",
         a="Three strands: claim detection (CheckThat!), health misinformation (datasets and studies), and LLMs as classifiers. Across all three, PT-PT is the gap.",
         act="follow_up", ents=[], cites=[], hier=[["N_13", "supercase"], ["N_16", "supercase"], ["N_19", "supercase"]], prag=[],
         creates=[], updates=[], relates=[],
         summary="Literature recap: three strands, with PT-PT as the common gap.",
         ref="Three-strand recap"),
    dict(id="N_23", date="2026-03-02",
         q="Can I use FakeRecogna even though my scope is PT-PT?",
         a="Not as your main data. It's Brazilian, and your scope is PT-PT only.",
         act="clarification_request", ents=["E_4"], cites=[], hier=[["N_21", "subcase"]], prag=[["N_21", "depends_on"]],
         creates=[], updates=[], relates=[["SN_3", "constrained_by"]],
         summary="FakeRecogna doesn't fit the PT-PT-only scope.",
         ref="FakeRecogna out of scope"),
    # ---- Method & data plan (Mar) -------------------------------------------------------
    dict(id="N_24", date="2026-03-09",
         q="Then I'll build my own PT-PT dataset: at least 2,000 annotated health claims.",
         a="Ambitious but valuable: it would be the first PT-PT resource of its kind. Plan the annotation carefully, since it will be the slowest part.",
         act="decision", ents=["E_5"], cites=[], hier=[["N_23", "subcase"]], prag=[["N_23", "depends_on"]],
         creates=["SN_4"], updates=[], relates=[],
         summary="Rita decides to build her own PT-PT dataset of at least 2,000 claims.",
         ref="Own 2,000-claim dataset"),
    dict(id="N_25", date="2026-03-09",
         q="How should I set up the annotation?",
         a="Write guidelines first: what counts as a health claim, what counts as misleading, with examples.",
         act="factual_question", ents=["E_5"], cites=[], hier=[["N_24", "subcase"]], prag=[["N_24", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks how to set up annotation; guidelines first.",
         ref="Annotation setup"),
    dict(id="N_26", date="2026-03-09",
         q="And to show the labels are reliable?",
         a="A second annotator on a subset. Your colleague Duarte could double-annotate part of the data, and you report Cohen's kappa for agreement.",
         act="information", ents=["E_16", "E_10"], cites=[], hier=[["N_25", "subcase"]], prag=[["N_25", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Duarte double-annotates a subset; agreement reported with Cohen's kappa.",
         ref="Second annotator Duarte"),
    dict(id="N_27", date="2026-03-09",
         q="For the model, I'll fine-tune BERTimbau as my main method.",
         a="A reasonable default: it's the standard Portuguese encoder, and fine-tuning is well understood.",
         act="decision", ents=["E_6"], cites=[], hier=[["N_2", "subcase"]], prag=[["N_22", "depends_on"]],
         creates=["SN_5"], updates=[], relates=[],
         summary="Main method: fine-tune BERTimbau.",
         ref="Fine-tune BERTimbau"),
    dict(id="N_28", date="2026-03-16",
         q="What hyperparameters should I start with?",
         a="Learning rate 2e-5, batch size 16, 3–4 epochs, and early stopping on a validation split.",
         act="follow_up", ents=["E_6"], cites=[], hier=[["N_27", "subcase"]], prag=[["N_27", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Starting hyperparameters for fine-tuning.",
         ref="Hyperparameters"),
    dict(id="N_29", date="2026-03-16",
         q="Base or large model?",
         a="BERTimbau-large usually scores a few points higher, but needs much more GPU memory and time.",
         act="information", ents=["E_6"], cites=[], hier=[["N_28", "subcase"]], prag=[["N_28", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Large scores higher but needs more GPU memory.",
         ref="Base vs large"),
    dict(id="N_30", date="2026-03-16",
         q="The only GPU I can use is the faculty server: one 16 GB card, shared.",
         a="That's a hard limit. 16 GB is tight for BERTimbau-large even with small batches.",
         act="information", ents=["E_18", "E_3"], cites=[], hier=[["N_27", "subcase"]], prag=[["N_29", "depends_on"]],
         creates=["SN_6"], updates=[], relates=[["SN_5", "constrained_by"]],
         summary="Compute is limited to one shared 16 GB GPU.",
         ref="16 GB GPU only"),
    dict(id="N_31", date="2026-03-23",
         q="Annotation update: in three weeks, Duarte and I have annotated 180 claims.",
         a="That's about 60 a week. Let's see what that means for the 2,000 target.",
         act="information", ents=["E_16", "E_5"], cites=[], hier=[["N_24", "subcase"]], prag=[["N_26", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Only 180 claims annotated in three weeks.",
         ref="180 claims annotated"),
    dict(id="N_32", date="2026-03-23",
         q="How long would 2,000 take at this rate?",
         a="About 33 weeks. That's well past 30 June.",
         act="follow_up", ents=["E_5"], cites=[], hier=[["N_31", "subcase"]], prag=[["N_31", "depends_on"]],
         creates=[], updates=[], relates=[["SN_4", "contradicts"]],
         summary="At this rate, 2,000 claims would take ~33 weeks.",
         ref="33 weeks needed"),
    dict(id="N_33", date="2026-03-30",
         q="I tried BERTimbau-large on the server: out of memory, even at batch size 4.",
         a="As feared. 16 GB isn't enough for large.",
         act="information", ents=["E_6", "E_18"], cites=[], hier=[["N_27", "subcase"]], prag=[["N_30", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="BERTimbau-large runs out of memory on 16 GB.",
         ref="Large OOMs"),
    dict(id="N_34", date="2026-03-30",
         q="And BERTimbau-base fits, but on my 180 claims it's barely above chance.",
         a="With so few labelled examples, base underfits. Fine-tuning needs far more data than you'll have.",
         act="follow_up", ents=["E_6"], cites=[], hier=[["N_33", "subcase"]], prag=[["N_33", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="BERTimbau-base fits but underfits on 180 claims.",
         ref="Base underfits"),
    # ---- Pivot (Apr) ---------------------------------------------------------------------
    dict(id="N_35", date="2026-04-06",
         q="I'm worried. Where does this leave the plan?",
         a="Two problems at once: the annotation pace [N_31] makes 2,000 claims impossible by June, and the GPU limit [N_33] makes fine-tuning large models impossible. The plan needs to change.",
         act="information", ents=[], cites=["N_31", "N_33"], hier=[], prag=[["N_31", "references"], ["N_33", "references"]],
         creates=[], updates=[], relates=[],
         summary="Annotation pace and GPU limit both break the current plan.",
         ref="Plan is broken"),
    dict(id="N_36", date="2026-04-06",
         q="So I drop fine-tuning as the main method?",
         a="Yes. Drop fine-tuning BERTimbau as the main method: it can't work with this data and this hardware.",
         act="decision", ents=["E_6"], cites=[], hier=[["N_35", "subcase"]], prag=[["N_27", "contradicts"]],
         creates=[], updates=[["SN_5", "reverted"]], relates=[],
         summary="Fine-tuning dropped as the main method.",
         ref="Drop fine-tuning"),
    dict(id="N_37", date="2026-04-06",
         q="What replaces it?",
         a="Zero-shot and few-shot classification with an LLM through an API (GPT-4o-mini, for example). It needs no training data beyond a few examples and no GPU of your own.",
         act="decision", ents=["E_7"], cites=[], hier=[["N_19", "subcase"]], prag=[["N_36", "depends_on"]],
         creates=["SN_7"], updates=[], relates=[["SN_6", "constrained_by"]],
         summary="Main method becomes zero/few-shot LLM classification.",
         ref="LLM zero/few-shot"),
    dict(id="N_38", date="2026-04-06",
         q="But doesn't that weaken the thesis? Anyone can call an API.",
         a="The novelty was never the model. It's the PT-PT question: whether classifiers built on Brazilian data work on European Portuguese. That question stays, and an LLM makes it easier to test.",
         act="disagreement", ents=[], cites=[], hier=[], prag=[["N_37", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Rita worries about novelty; the variety question is the contribution.",
         ref="Novelty concern"),
    dict(id="N_39", date="2026-04-13",
         q="And the 2,000-claim dataset? Honestly, it's not going to happen.",
         a="Agreed. Abandon the 2,000-claim goal; the time is better spent on experiments.",
         act="decision", ents=["E_5"], cites=[], hier=[["N_24", "subcase"]], prag=[["N_24", "contradicts"]],
         creates=[], updates=[["SN_4", "abandoned"]], relates=[],
         summary="The 2,000-claim dataset goal is abandoned.",
         ref="Dataset goal abandoned"),
    dict(id="N_40", date="2026-04-13",
         q="Then what data do I use?",
         a="FakeRecogna for few-shot examples and development, and your own annotated PT-PT claims, topped up to 400, as the test set. 400 is reachable in a few more weeks.",
         act="decision", ents=["E_4", "E_5"], cites=[], hier=[["N_39", "subcase"]], prag=[["N_39", "depends_on"]],
         creates=["SN_8"], updates=[], relates=[],
         summary="Data: FakeRecogna plus 400 own PT-PT claims as test set.",
         ref="FakeRecogna + 400 PT-PT"),
    dict(id="N_41", date="2026-04-13",
         q="But FakeRecogna is Brazilian, and my scope is PT-PT only.",
         a="Then the scope has to widen: include both PT-PT and PT-BR. Without PT-BR data, there's nothing to learn from.",
         act="decision", ents=["E_14", "E_15"], cites=[], hier=[["N_8", "subcase"]], prag=[["N_8", "revises"]],
         creates=[], updates=[["SN_3", "revised"]], relates=[],
         summary="Scope widened to PT-PT plus PT-BR.",
         ref="Scope: PT-PT + PT-BR"),
    dict(id="N_42", date="2026-04-13",
         q="Does RQ2 still make sense then?",
         a="It gets sharper. Reframe RQ2 as a transfer question: how well does a classifier built with PT-BR data and examples work on PT-PT news? That's exactly what FakeRecogna plus your 400 PT-PT claims can answer.",
         act="decision", ents=["E_4"], cites=[], hier=[["N_6", "subcase"]], prag=[["N_6", "revises"]],
         creates=[], updates=[["SN_2", "revised"]], relates=[],
         summary="RQ2 reframed as a PT-BR to PT-PT transfer question.",
         ref="RQ2 reframed as transfer"),
    dict(id="N_43", date="2026-04-13",
         q="Let me make sure I have the new plan straight.",
         a="Method: LLM zero/few-shot [N_37]. Data: FakeRecogna plus 400 own PT-PT claims [N_40]. RQ2: transfer from PT-BR to PT-PT [N_42]. Scope: both varieties.",
         act="follow_up", ents=[], cites=["N_37", "N_40", "N_42"], hier=[["N_37", "supercase"], ["N_40", "supercase"], ["N_42", "supercase"]], prag=[],
         creates=[], updates=[], relates=[],
         summary="Recap of the post-pivot plan.",
         ref="New plan recap"),
    # ---- Experiments (Apr-May) ---------------------------------------------------------------
    dict(id="N_44", date="2026-04-20",
         q="With only two annotators, is my annotation reliable enough to report?",
         a="It can be, if the agreement is good; that's what the kappa will tell us.",
         act="factual_question", ents=["E_16", "E_10"], cites=[], hier=[["N_40", "subcase"]], prag=[],
         creates=["SN_9"], updates=[], relates=[],
         summary="Asks whether two-annotator labels are reliable enough.",
         ref="Annotation reliable?"),
    dict(id="N_45", date="2026-04-20",
         q="How many claims should we both annotate for the kappa?",
         a="Around 100 of the 400, sampled at random, annotated independently before you compare.",
         act="information", ents=["E_10"], cites=[], hier=[["N_44", "subcase"]], prag=[["N_44", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Double-annotate ~100 random claims for kappa.",
         ref="100 for kappa"),
    dict(id="N_46", date="2026-04-20",
         q="How should I design the zero-shot prompt?",
         a="Give the model a precise definition of a misleading health claim and a fixed label set, and ask for the label only.",
         act="factual_question", ents=[], cites=[], hier=[["N_37", "subcase"]], prag=[["N_37", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks how to design the zero-shot prompt.",
         ref="Prompt design"),
    dict(id="N_47", date="2026-04-20",
         q="Should the definition come from my annotation guidelines?",
         a="Yes, use exactly the guideline definitions, so the model and the annotators apply the same criteria.",
         act="information", ents=[], cites=[], hier=[["N_46", "subcase"]], prag=[["N_46", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="The prompt uses the annotation guideline definitions.",
         ref="Guideline definitions"),
    dict(id="N_48", date="2026-04-27",
         q="For few-shot, how do I pick the examples?",
         a="Balanced across labels, and short.",
         act="follow_up", ents=[], cites=[], hier=[["N_46", "same_level"]], prag=[["N_47", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks how to select few-shot examples.",
         ref="Few-shot selection"),
    dict(id="N_49", date="2026-04-27",
         q="From which data, though?",
         a="From FakeRecogna (PT-BR), testing on your PT-PT claims. That makes the few-shot setting itself a test of RQ2's transfer question.",
         act="information", ents=["E_4"], cites=[], hier=[["N_48", "subcase"]], prag=[["N_48", "resolves"], ["N_42", "references"]],
         creates=[], updates=[], relates=[["SN_2", "supports"]],
         summary="Few-shot examples come from PT-BR FakeRecogna, testing on PT-PT.",
         ref="PT-BR examples, PT-PT test"),
    dict(id="N_50", date="2026-05-04",
         q="First results with GPT-4o-mini on the PT-PT test set: zero-shot macro-F1 0.61, few-shot 0.68. Just in time for my midterm presentation next week.",
         a="Good first numbers to present: few-shot helps by 7 points even with Brazilian examples.",
         act="information", ents=["E_7", "E_17", "E_13"], cites=[], hier=[["N_37", "subcase"]], prag=[["N_49", "depends_on"]],
         creates=[], updates=[], relates=[["SN_7", "supports"]],
         summary="GPT-4o-mini: zero-shot 0.61, few-shot 0.68 macro-F1 on PT-PT.",
         ref="First results 0.61/0.68"),
    dict(id="N_51", date="2026-05-04",
         q="Is 0.68 actually good?",
         a="For a hard, subjective task with no PT-PT training data it's respectable; CheckThat! systems on similar tasks land in the 0.6–0.8 range.",
         act="follow_up", ents=["E_17"], cites=[], hier=[["N_50", "subcase"]], prag=[["N_50", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="0.68 is respectable for the task.",
         ref="0.68 respectable"),
    dict(id="N_52", date="2026-05-04",
         q="Duarte and I finished the 100 double-annotated claims: kappa is 0.71.",
         a="0.71 is 'substantial' agreement on the usual scale. The annotation is reliable enough to report.",
         act="information", ents=["E_16", "E_10"], cites=[], hier=[["N_45", "subcase"]], prag=[["N_44", "resolves"]],
         creates=[], updates=[["SN_9", "resolved"]], relates=[["SN_9", "resolves"]],
         summary="Kappa 0.71: substantial agreement, reliable enough to report.",
         ref="Kappa 0.71"),
    dict(id="N_53", date="2026-05-11",
         q="Meeting with Prof. Almeida. He says having no fine-tuned baseline at all is a red flag for any examiner.",
         a="He has a point: without a trained baseline, examiners can't tell whether the LLM is actually good or just the only thing tried.",
         act="information", ents=["E_2"], cites=[], hier=[], prag=[["N_36", "contradicts"]],
         creates=[], updates=[], relates=[],
         summary="Supervisor insists on a fine-tuned baseline.",
         ref="Baseline required"),
    dict(id="N_54", date="2026-05-11",
         q="But we dropped fine-tuning because it didn't fit on the GPU!",
         a="BERTimbau-large didn't fit. A smaller multilingual model would, and it only needs to be a baseline, not the main method.",
         act="disagreement", ents=["E_18"], cites=[], hier=[], prag=[["N_53", "depends_on"]],
         creates=[], updates=[], relates=[["SN_6", "constrained_by"]],
         summary="Rita objects that fine-tuning didn't fit on the GPU.",
         ref="GPU objection"),
    dict(id="N_55", date="2026-05-11",
         q="Which model then?",
         a="XLM-R-base: multilingual, fits comfortably on 16 GB, and fine-tuned on FakeRecogna it gives a proper trained baseline. The LLM stays the main method, compared against XLM-R.",
         act="decision", ents=["E_19", "E_4"], cites=[], hier=[["N_53", "subcase"]], prag=[["N_37", "revises"], ["N_54", "resolves"]],
         creates=["SN_10"], updates=[["SN_7", "revised"]], relates=[],
         summary="Add a fine-tuned XLM-R-base baseline; the LLM remains the main method.",
         ref="XLM-R baseline added"),
    dict(id="N_56", date="2026-05-18",
         q="XLM-R results: fine-tuned on FakeRecogna, it gets 0.64 macro-F1 on held-out PT-BR data.",
         a="0.64 in-variety is a solid baseline.",
         act="information", ents=["E_19", "E_17"], cites=[], hier=[["N_55", "subcase"]], prag=[["N_55", "depends_on"]],
         creates=[], updates=[], relates=[["SN_10", "supports"]],
         summary="XLM-R: 0.64 macro-F1 in-variety (PT-BR).",
         ref="XLM-R 0.64 PT-BR"),
    dict(id="N_57", date="2026-05-18",
         q="And on the PT-PT test set it drops to 0.52.",
         a="A 12-point drop across varieties. That's a clear transfer gap, exactly what RQ2 asks about, and the LLM's 0.68 holds up much better.",
         act="information", ents=["E_19", "E_17"], cites=[], hier=[["N_56", "same_level"]], prag=[["N_56", "depends_on"]],
         creates=[], updates=[], relates=[["SN_2", "supports"]],
         summary="XLM-R drops to 0.52 on PT-PT: a clear transfer gap.",
         ref="XLM-R 0.52 PT-PT"),
    dict(id="N_58", date="2026-05-18",
         q="Should I replace GPT-4o-mini with Llama-3.1-8B running locally, for reproducibility?",
         a="Worth considering: API models change without notice.",
         act="factual_question", ents=["E_7", "E_8"], cites=[], hier=[["N_37", "subcase"]], prag=[],
         creates=["SN_14"], updates=[], relates=[],
         summary="Asks whether to replace GPT-4o-mini with a local Llama-3.1-8B.",
         ref="Llama for reproducibility?"),
    dict(id="N_59", date="2026-05-18",
         q="What are the trade-offs?",
         a="Llama is fully reproducible and free, but will likely score lower; GPT-4o-mini scores higher but may change or disappear. Reporting only one hides something either way.",
         act="information", ents=["E_7", "E_8"], cites=[], hier=[["N_58", "subcase"]], prag=[["N_58", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Trade-offs between local Llama and API GPT-4o-mini.",
         ref="Trade-offs"),
    dict(id="N_60", date="2026-05-25",
         q="Prof. Almeida suggested also submitting a short paper to PROPOR 2026. Should I?",
         a="A paper would strengthen your CV, and the transfer result is publishable. Let's plan for it.",
         act="decision", ents=["E_2", "E_11"], cites=[], hier=[["N_1", "same_level"]], prag=[],
         creates=["SN_12"], updates=[], relates=[],
         summary="Decides to submit a short paper to PROPOR 2026.",
         ref="PROPOR paper planned"),
    dict(id="N_61", date="2026-05-25",
         q="When is the PROPOR deadline?",
         a="20 June, so ten days before your thesis deadline.",
         act="information", ents=["E_11"], cites=[], hier=[["N_60", "subcase"]], prag=[["N_60", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="PROPOR deadline is 20 June.",
         ref="PROPOR deadline 20 June"),
    dict(id="N_62", date="2026-05-25",
         q="On the Llama question: can I just report both?",
         a="Yes, report both. GPT-4o-mini as the main result and Llama-3.1-8B as the reproducible reference; the gap between them is itself informative.",
         act="decision", ents=["E_7", "E_8"], cites=[], hier=[["N_58", "subcase"]], prag=[["N_58", "resolves"]],
         creates=[], updates=[["SN_14", "resolved"]], relates=[["SN_14", "resolves"]],
         summary="Both LLMs will be reported.",
         ref="Report both LLMs"),
    # ---- Deadlines & writing (Jun) ------------------------------------------------------------
    dict(id="N_63", date="2026-06-01",
         q="I'm behind. The error analysis isn't started and there's a month left before 30 June.",
         a="That's tight for experiments, error analysis and writing.",
         act="information", ents=["E_12"], cites=[], hier=[], prag=[["N_12", "references"]],
         creates=[], updates=[], relates=[["SN_11", "constrained_by"]],
         summary="Analysis is behind schedule with a month left.",
         ref="Behind schedule"),
    dict(id="N_64", date="2026-06-01",
         q="Good news: the faculty approved my extension request. The new deadline is 15 September.",
         a="That changes everything: the deadline is now 15 September, which leaves room for a proper error analysis.",
         act="information", ents=["E_3", "E_12"], cites=[], hier=[], prag=[["N_12", "revises"]],
         creates=[], updates=[["SN_11", "revised"]], relates=[],
         summary="Extension approved: deadline moves to 15 September.",
         ref="Deadline 15 September"),
    dict(id="N_65", date="2026-06-01",
         q="Should I still try for the PROPOR paper?",
         a="The paper deadline is 20 June regardless of your extension. Writing it now would take the time the extension just gave you.",
         act="factual_question", ents=["E_11"], cites=[], hier=[["N_60", "subcase"]], prag=[["N_60", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks whether to still attempt the PROPOR paper.",
         ref="PROPOR still?"),
    dict(id="N_66", date="2026-06-01",
         q="Then I'll skip PROPOR and focus on the thesis.",
         a="Sensible. You can turn the thesis into a paper for a later venue once it's submitted.",
         act="decision", ents=["E_11"], cites=[], hier=[["N_65", "subcase"]], prag=[["N_60", "contradicts"]],
         creates=[], updates=[["SN_12", "reverted"]], relates=[],
         summary="PROPOR submission dropped.",
         ref="Skip PROPOR"),
    dict(id="N_67", date="2026-06-08",
         q="Starting the error analysis. Where does the transfer from PT-BR to PT-PT fail most?",
         a="Look at the PT-PT claims that XLM-R gets wrong but classifies correctly on similar PT-BR items.",
         act="information", ents=[], cites=[], hier=[["N_42", "subcase"]], prag=[["N_57", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Error analysis starts on PT-BR to PT-PT transfer failures.",
         ref="Error analysis start"),
    dict(id="N_68", date="2026-06-08",
         q="A lot of errors involve vocabulary and idioms that differ between the varieties.",
         a="That's a classic variety effect: everyday words and set phrases differ enough to confuse a model trained on Brazilian text.",
         act="information", ents=["E_14", "E_15"], cites=[], hier=[["N_67", "subcase"]], prag=[["N_67", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Many errors involve vocabulary and idioms that differ between varieties.",
         ref="Vocabulary errors"),
    dict(id="N_69", date="2026-06-08",
         q="And institution names: claims about the SNS and the DGS get misclassified much more than claims about the SUS and Anvisa.",
         a="Health institutions are country-specific (Portugal's SNS and DGS vs Brazil's SUS and Anvisa), so claims about them look unfamiliar to a PT-BR-trained model.",
         act="information", ents=["E_14", "E_15"], cites=[], hier=[["N_67", "subcase"]], prag=[["N_67", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Claims about Portuguese health institutions are misclassified more often.",
         ref="Institution-name errors"),
    dict(id="N_70", date="2026-06-08",
         q="How should I present the error analysis?",
         a="Group errors into categories (vocabulary, institutions, other), give counts per category, and two or three examples each.",
         act="follow_up", ents=[], cites=[], hier=[["N_67", "subcase"]], prag=[["N_69", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Present errors by category with counts and examples.",
         ref="Error categories"),
    dict(id="N_71", date="2026-06-15",
         q="Time to plan the writing. What structure?",
         a="Six chapters: introduction, related work, data, method, results and error analysis, conclusions. Keep related work before method, so the reader knows the gap before seeing your approach.",
         act="decision", ents=[], cites=[], hier=[["N_1", "subcase"]], prag=[],
         creates=["SN_13"], updates=[], relates=[],
         summary="Six-chapter thesis structure, related work before method.",
         ref="Six chapters"),
    dict(id="N_72", date="2026-06-15",
         q="What goes into the method chapter?",
         a="The models, the prompts and the evaluation protocol.",
         act="factual_question", ents=[], cites=[], hier=[["N_71", "subcase"]], prag=[["N_71", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Asks what goes into the method chapter.",
         ref="Method chapter?"),
    dict(id="N_73", date="2026-06-15",
         q="Which models exactly, and in what role?",
         a="GPT-4o-mini and Llama-3.1-8B as the zero/few-shot classifiers, XLM-R-base as the fine-tuned baseline, and macro-F1 on the 400 PT-PT claims as the main metric.",
         act="information", ents=["E_7", "E_8", "E_19", "E_17"], cites=[], hier=[["N_72", "subcase"]], prag=[["N_72", "resolves"]],
         creates=[], updates=[], relates=[],
         summary="Method chapter content: two LLMs, XLM-R baseline, macro-F1 on 400 PT-PT claims.",
         ref="Method chapter content"),
    dict(id="N_74", date="2026-06-15",
         q="Writing the introduction, I realised I'm not sure what my RQs are anymore. What were they, and do they still match what I did?",
         a="You set them back in February [N_6] and changed RQ2 in April [N_42]; let's check them against the current work.",
         act="factual_question", ents=[], cites=["N_6", "N_42"], hier=[], prag=[["N_6", "references"], ["N_42", "references"]],
         creates=[], updates=[], relates=[],
         summary="Rita asks what her RQs are and whether they still match the work.",
         ref="What are my RQs?"),
    dict(id="N_75", date="2026-06-15",
         q="So what do I write?",
         a="RQ1 is unchanged: can models detect misleading health claims in Portuguese news. RQ2 is now the transfer question: how well does a classifier built on PT-BR work on PT-PT. The introduction has to explain that pivot honestly.",
         act="information", ents=[], cites=[], hier=[["N_74", "subcase"]], prag=[["N_74", "resolves"]],
         creates=[], updates=[], relates=[["SN_2", "supports"]],
         summary="RQ1 unchanged, RQ2 is now transfer; the intro must explain the pivot.",
         ref="RQs confirmed"),
    dict(id="N_76", date="2026-06-22",
         q="What goes in the limitations section?",
         a="Three things: the small test set, since the 2,000-claim dataset was abandoned [N_39]; only two annotators, though with kappa 0.71 [N_52]; and the single 16 GB GPU [N_30], which ruled out large fine-tuned models.",
         act="request", ents=["E_5", "E_10", "E_18"], cites=["N_30", "N_39", "N_52"], hier=[["N_71", "subcase"]], prag=[["N_39", "references"], ["N_52", "references"], ["N_30", "references"]],
         creates=[], updates=[], relates=[],
         summary="Limitations: small test set, two annotators, single 16 GB GPU.",
         ref="Limitations"),
    dict(id="N_77", date="2026-06-22",
         q="Can you summarise every change of plan, so the story in the thesis is honest?",
         a="Four pivots: fine-tuning was dropped as the main method [N_36]; the scope widened from PT-PT to both varieties [N_41]; a fine-tuned XLM-R baseline came back at the supervisor's request [N_55]; and the PROPOR paper was dropped after the extension [N_66].",
         act="follow_up", ents=[], cites=["N_36", "N_41", "N_55", "N_66"], hier=[["N_36", "supercase"], ["N_41", "supercase"], ["N_55", "supercase"], ["N_66", "supercase"]], prag=[],
         creates=[], updates=[], relates=[],
         summary="Summary of the four changes of plan.",
         ref="All pivots summarised"),
    dict(id="N_78", date="2026-06-22",
         q="I sent chapters 1–3 to Prof. Almeida.",
         a="Good. Keep writing the results chapter while he reads.",
         act="information", ents=["E_2"], cites=[], hier=[["N_71", "subcase"]], prag=[["N_71", "depends_on"]],
         creates=[], updates=[], relates=[["SN_13", "supports"]],
         summary="Chapters 1-3 sent to the supervisor.",
         ref="Chapters 1-3 sent"),
    dict(id="N_79", date="2026-06-26",
         q="He's happy with them. His only comment: tighten the evaluation chapter.",
         a="That's a good position to be in by the end of June, with more than two months until the deadline.",
         act="information", ents=["E_2"], cites=[], hier=[], prag=[["N_78", "depends_on"]],
         creates=[], updates=[], relates=[],
         summary="Supervisor approves chapters 1-3.",
         ref="Chapters approved"),
    dict(id="N_80", date="2026-09-11",
         q="I submitted the thesis today, four days before the 15 September deadline!",
         a="Congratulations, Rita! From 'misinformation in Portuguese news' to a submitted thesis with a real transfer finding.",
         act="information", ents=["E_1", "E_12"], cites=[], hier=[], prag=[["N_1", "resolves"], ["N_64", "depends_on"]],
         creates=[], updates=[["SN_1", "achieved"]], relates=[],
         summary="Thesis submitted on 11 September.",
         ref="Thesis submitted"),
]

node_index = {n["id"]: i for i, n in enumerate(NODES)}

# --- Validate backward-in-time edges ---
for n in NODES:
    for tgt, _ in n["hier"] + n["prag"]:
        assert node_index[tgt] < node_index[n["id"]], f"{n['id']} -> {tgt} not backward"

# --- recurrence_count / retrieval_count ---
recurrence = {n["id"]: 0 for n in NODES}
for n in NODES:
    for tgt, _ in n["hier"] + n["prag"]:
        recurrence[tgt] += 1

# --- epistemic_status / epistemic_history ---
status, history = {}, {}
for n in NODES:
    default = "open" if n["act"] in OPEN_DEFAULT_ACTS else "resolved"
    status[n["id"]] = default
    history[n["id"]] = [[n["id"], "creation", default]]

TRANSITION = {
    "revises": lambda cur: "superseded",
    "resolves": lambda cur: "resolved" if cur != "superseded" else "superseded",
    "contradicts": lambda cur: "contested" if cur != "superseded" else "superseded",
}
for n in NODES:
    for tgt, label in n["prag"]:
        if label not in TRANSITION:
            continue
        new = TRANSITION[label](status[tgt])
        history[tgt].append([n["id"], label, new])
        status[tgt] = new

# --- entities.mentioned_in ---
mentioned_in = {eid: [] for eid in ENTITIES}
for n in NODES:
    for eid in n["ents"]:
        mentioned_in[eid].append(n["id"])

# --- state nodes: status + last_updated_turn ---
sn_status = {sid: INITIAL_STATUS[d["type"]] for sid, d in STATE_NODE_DEFS.items()}
sn_creation_turn = {}
sn_last_updated = {sid: {"updates": [], "relates": []} for sid in STATE_NODE_DEFS}
sn_label = {sid: d["label"] for sid, d in STATE_NODE_DEFS.items()}
for n in NODES:
    for sid in n["creates"]:
        sn_creation_turn[sid] = n["id"]
    for sid, new_status in n["updates"]:
        sn_status[sid] = new_status
        sn_last_updated[sid]["updates"].append([n["id"], new_status])
        override = LABEL_OVERRIDES.get((sid, n["id"]))
        if override:
            sn_label[sid] = override
    for sid, relation in n["relates"]:
        sn_last_updated[sid]["relates"].append([n["id"], relation])

# --- Assemble output ---
interaction_nodes = {}
for n in NODES:
    interaction_nodes[n["id"]] = {
        "question": n["q"],
        "answer": n["a"],
        "embedding": f"<vector: {n['id']} question+answer>",
        "named_entities": n["ents"],
        "citations": n["cites"],
        "speech_act": n["act"],
        "epistemic_status": status[n["id"]],
        "epistemic_history": history[n["id"]],
        "recurrence_count": recurrence[n["id"]],
        "retrieval_count": recurrence[n["id"]],
        "summary": n["summary"],
        "reference": n["ref"],
        "edges": {"hierarchical": n["hier"], "pragmatic": n["prag"]},
        "state_node_links": {
            k: v for k, v in {
                "creates": n["creates"], "updates": n["updates"], "relates": n["relates"],
            }.items() if v
        },
    }

entities_out = {
    eid: {"type": d["type"], "name": d["name"], "mentioned_in": mentioned_in[eid]}
    for eid, d in ENTITIES.items()
}

state_nodes_out = {
    sid: {
        "type": d["type"],
        "label": sn_label[sid],
        "embedding": f"<vector: {sid} label>",
        "creation_turn": sn_creation_turn[sid],
        "status": sn_status[sid],
        "last_updated_turn": sn_last_updated[sid],
    }
    for sid, d in STATE_NODE_DEFS.items()
}

ground_truth = {
    "conversation_id": "thesis_planning",
    "domain": "MSc thesis planning over seven months (misleading health claims in Portuguese news)",
    "schema_note": (
        "Mirrors INESCTEC_RESEARCH.md section 3/4 output schema, same convention as "
        "conversations/marathon_trip. Domain entity types (domain_config.json): dataset, model, venue, concept. "
        "80 turns with real gaps between sessions (up to 11 weeks before N_80). Built to exercise goal: "
        "abandoned (SN_4, the first in any corpus), decision reverted and later partly brought back in a "
        "different form (SN_5 fine-tuning -> SN_7 LLMs -> SN_10 XLM-R baseline), scope and deadline "
        "constraints revised (SN_3, SN_11), and long-range recall (RQs set at N_6, recalled at N_74)."
    ),
    "schema_findings": [
        {
            "raised_at_node": "N_39",
            "issue": "Abandoning a goal (SN_4) has no StateRelation label, the same issue marathon_trip and "
                     "tech_support raised. Recorded via state_node_links.updates alone.",
            "proposed_direction": "Same resolution as the earlier corpora: status change via updates, no paired "
                                   "relates entry.",
        },
        {
            "raised_at_node": "N_55",
            "issue": "Fine-tuning returns as a baseline (SN_10) after being reverted as the main method (SN_5). "
                     "SN_5 cannot be re-activated (terminal), and the new decision differs in model (XLM-R, not "
                     "BERTimbau) and role (baseline, not main method). N_53 contradicts N_36, the turn that dropped it.",
            "proposed_direction": "New state node, plus the contradicts edge to the dropping turn. The graph links "
                                   "SN_5 and SN_10 only through interaction edges; probe p2 tests whether answers "
                                   "follow that link.",
        },
        {
            "raised_at_node": "N_80",
            "issue": "The outline left open whether SN_1 'achieved' means a finished draft or the submission. The "
                     "corpus uses the actual submission (N_80, 11 September, after an 11-week gap).",
            "proposed_direction": "Goals are achieved when their stated outcome happens ('submit a thesis'), not "
                                   "when work towards it is mostly done.",
        },
    ],
    "interaction_nodes": interaction_nodes,
    "entities": entities_out,
    "state_nodes": state_nodes_out,
}

corpus = [
    {"id": n["id"], "date": n["date"], "turns": [
        {"speaker": "user", "text": n["q"]},
        {"speaker": "assistant", "text": n["a"]},
    ]}
    for n in NODES
]

out_dir = Path(__file__).resolve().parent
(out_dir / "corpus.json").write_text(json.dumps(corpus, indent=2, ensure_ascii=False) + "\n")
(out_dir / "ground_truth.json").write_text(json.dumps(ground_truth, indent=2, ensure_ascii=False) + "\n")

print(f"Wrote {len(NODES)} interaction nodes, {len(ENTITIES)} entities, {len(STATE_NODE_DEFS)} state nodes.")
print("Epistemic status:", dict(Counter(status.values())))
print("Speech acts:", dict(Counter(n["act"] for n in NODES)))
print("Hierarchical:", dict(Counter(l for n in NODES for _, l in n["hier"])))
print("Pragmatic:", dict(Counter(l for n in NODES for _, l in n["prag"])))
print("State nodes:", dict(Counter((d["type"], sn_status[sid]) for sid, d in STATE_NODE_DEFS.items())))
print("Entity types:", dict(Counter(d["type"] for d in ENTITIES.values())))
